# coding: utf-8

"""
    dynamicPricing

    API for dynamic pricing calculations.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="dynamicPricing",
    description="API for dynamic pricing calculations.",
    version="1.0",
)

app.include_router(DefaultApiRouter)
