/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.DynamicPricingPost200Response;
import org.openapitools.model.DynamicPricingPostRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-07-08T20:21:18.246317500+05:30[Asia/Colombo]", comments = "Generator version: 7.9.0")
@Validated
@Tag(name = "dynamicPricing", description = "the dynamicPricing API")
public interface DynamicPricingApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /dynamicPricing : Gets the price details
     *
     * @param dynamicPricingPostRequest  (required)
     * @return Success response with calculated pricing details (status code 200)
     */
    @Operation(
        operationId = "dynamicPricingPost",
        summary = "Gets the price details",
        responses = {
            @ApiResponse(responseCode = "200", description = "Success response with calculated pricing details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DynamicPricingPost200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/dynamicPricing",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<DynamicPricingPost200Response> dynamicPricingPost(
        @Parameter(name = "DynamicPricingPostRequest", description = "", required = true) @Valid @RequestBody DynamicPricingPostRequest dynamicPricingPostRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"Result\" : { \"Reasoning\" : \"Reasoning\", \"SuggestedPrice\" : 0.8008281904610115 } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
