# coding: utf-8

"""
    DynamicPricing

    Gives items pricing dynamically

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="DynamicPricing",
    description="Gives items pricing dynamically",
    version="v1",
)

app.include_router(DefaultApiRouter)
